name: test-functions

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test-functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v2
      - uses: gperrett/thinkCausal_dev/.github/workflows/setup-renv@master
      - name: Run tests
        run: source('thinkCausal/tests/testthat.R')
        shell: Rscript {0}
