name: test-functions

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test-functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: Rscript -e "install.packages(c('testthat'))"
      - name: Run tests
        run: Rscript -e "setwd('thinkCausal'); source('tests/testthat.R')""
