name: test-functions

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test-functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v2
      - uses: joemarlo/thinkCausal_dev/.github/setup-renv@workflows
      - name: Run tests
        shell: Rscript {0}
        working-directory: thinkCausal
        run: source('tests/testthat.R')

