name: test-functions

on:
  push:
    branches: [main, master, dev, workflows]
  pull_request:
    branches: [main, master, dev, workflows]

env:
  RENV_CONFIG_SANDBOX_ENABLED: False
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test-functions:
    timeout-minutes: 45
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
      - uses: priism-center/thinkCausal_dev/.github/setup-renv@master
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tests
        shell: Rscript {0}
        run: print(getwd()); testthat::test_local();
        working-directory: thinkCausal

