name: test-functions

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test-functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: thinkCausal
          extra-packages: testthat
      - name: Run tests
        run: Rscript -e "source('thinkCausal/tests/testthat.R')"

