name: test-functions

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test-functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-renv@v2
      - name: Run tests
        run: Rscript -e "install.packages('testthat'); source('thinkCausal/tests/testthat.R')"

